### ISSUE TITLE
ObjectUtility.CheckInherit(Type child, Type parent)

### ISSUE THREAD

**Issue by wen-carl** [code-jar/MaterialDesignDemo#1]
There is something wrong with the method, it can't work in RecyclerViewAdapter.

**Comment by wen-carl** [comment]
In the internet, I find this:(https://codeday.me/bug/20170326/6172.html)
public bool IsSameOrSubclass(Type potentialBase, Type potentialDescendant)
{
    return potentialDescendant.IsSubclassOf(potentialBase)
           || potentialDescendant == potentialBase;
}

**Comment by code-jar** [comment]
Thanks
